<?php

namespace ContainerGFm5xCd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAppService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6E5uU93.App\Entity\UserApp' shared service.
     *
     * @return \App\Entity\UserApp
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.6E5uU93": it references class "App\\Entity\\UserApp" but no such service exists.');
    }
}
