<?php

namespace ContainerNhLk1mM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EF4EZN4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eF4EZN4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eF4EZN4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'instrument' => ['privates', '.errored..service_locator.eF4EZN4.App\\Entity\\Instrument', NULL, 'Cannot autowire service ".service_locator.eF4EZN4": it references class "App\\Entity\\Instrument" but no such service exists.'],
        ], [
            'instrument' => 'App\\Entity\\Instrument',
        ]);
    }
}
