<?php

namespace Container79B77z7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O745I24Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o745I24' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o745I24'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'channel' => ['privates', '.errored..service_locator.o745I24.App\\Entity\\Channel', NULL, 'Cannot autowire service ".service_locator.o745I24": it references class "App\\Entity\\Channel" but no such service exists.'],
            'cookieJwtProvider' => ['privates', 'App\\Service\\CookieJwtProvider', 'getCookieJwtProviderService', true],
            'messageRepository' => ['privates', 'App\\Repository\\MessageRepository', 'getMessageRepositoryService', true],
        ], [
            'channel' => 'App\\Entity\\Channel',
            'cookieJwtProvider' => 'App\\Service\\CookieJwtProvider',
            'messageRepository' => 'App\\Repository\\MessageRepository',
        ]);
    }
}
