<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXiEdXjk\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXiEdXjk/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXiEdXjk.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXiEdXjk\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerXiEdXjk\App_KernelProdContainer([
    'container.build_hash' => 'XiEdXjk',
    'container.build_id' => 'aabba00d',
    'container.build_time' => 1627237520,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXiEdXjk');
