<?php

namespace ContainerXiEdXjk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGenreTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\GenreType' shared autowired service.
     *
     * @return \App\Form\Type\GenreType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Type\\GenreType'] = new \App\Form\Type\GenreType();
    }
}
