<?php

namespace ContainerXiEdXjk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstrumentTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\InstrumentType' shared autowired service.
     *
     * @return \App\Form\Type\InstrumentType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\Type\\InstrumentType'] = new \App\Form\Type\InstrumentType();
    }
}
