<?php

namespace ContainerXiEdXjk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstrumentRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\InstrumentRepository' shared autowired service.
     *
     * @return \App\Repository\InstrumentRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\InstrumentRepository'] = new \App\Repository\InstrumentRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
