<?php

namespace ContainerXiEdXjk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getImageUploaderService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\ImageUploader' shared autowired service.
     *
     * @return \App\Service\ImageUploader
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Service\\ImageUploader'] = new \App\Service\ImageUploader(($container->privates['slugger'] ?? ($container->privates['slugger'] = new \Symfony\Component\String\Slugger\AsciiSlugger('en'))));
    }
}
