<?php

namespace ContainerXiEdXjk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationUserAppTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\RegistrationUserAppType' shared autowired service.
     *
     * @return \App\Form\RegistrationUserAppType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\RegistrationUserAppType'] = new \App\Form\RegistrationUserAppType();
    }
}
