<?php

namespace ContainerXiEdXjk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserAppRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\UserAppRepository' shared autowired service.
     *
     * @return \App\Repository\UserAppRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UserAppRepository'] = new \App\Repository\UserAppRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
