<?php

namespace ContainerWH4ZSWG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9UEvW4_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9UEvW4.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9UEvW4.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'imageUploader' => ['privates', 'App\\Service\\ImageUploader', 'getImageUploaderService', true],
            'instrument' => ['privates', '.errored..service_locator.9UEvW4..App\\Entity\\Instrument', NULL, 'Cannot autowire service ".service_locator.9UEvW4.": it references class "App\\Entity\\Instrument" but no such service exists.'],
        ], [
            'imageUploader' => 'App\\Service\\ImageUploader',
            'instrument' => 'App\\Entity\\Instrument',
        ]);
    }
}
