<?php

namespace ContainerBYCKP23;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AB9d_UJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AB9d.uJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AB9d.uJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'styleRepository' => ['privates', 'App\\Repository\\StyleRepository', 'getStyleRepositoryService', true],
        ], [
            'styleRepository' => 'App\\Repository\\StyleRepository',
        ]);
    }
}
