<?php

namespace ContainerBYCKP23;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInstrumentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9UEvW4..App\Entity\Instrument' shared service.
     *
     * @return \App\Entity\Instrument
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9UEvW4.": it references class "App\\Entity\\Instrument" but no such service exists.');
    }
}
