<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNhLk1mM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNhLk1mM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNhLk1mM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNhLk1mM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNhLk1mM\App_KernelDevDebugContainer([
    'container.build_hash' => 'NhLk1mM',
    'container.build_id' => 'aea97156',
    'container.build_time' => 1627654763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNhLk1mM');
