<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPZzbAxJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPZzbAxJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPZzbAxJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPZzbAxJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPZzbAxJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'PZzbAxJ',
    'container.build_id' => '490ed348',
    'container.build_time' => 1627752716,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPZzbAxJ');
