<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBYCKP23\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBYCKP23/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBYCKP23.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBYCKP23\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBYCKP23\App_KernelDevDebugContainer([
    'container.build_hash' => 'BYCKP23',
    'container.build_id' => '6d2148a6',
    'container.build_time' => 1627907670,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBYCKP23');
